### ISSUE TITLE
Navigation options have disappeared since Webextensions port

### ISSUE THREAD

**Issue by gizmecano** [arantius/uppity#3]
It seems that the [rewrite for WebExtensions support](https://addons.mozilla.org/fr/firefox/addon/uppity/) no more includes any option to navigate into the address tree but only to reach up to the immediate top level.

Do you plan to restore the previous options?

**Comment by gizmecano** [comment]
Sorry for not reading the release [comment that you wrote](https://addons.mozilla.org/fr/firefox/addon/uppity/versions/?page=1#version-2.0):

> (...) with fewer features of course, because WebExt APIs are awful and broken

But nevertheless, the question is still relevant, as these navigation options were really convenient.

**Comment by arantius** [comment]
Yes, but https://bugzilla.mozilla.org/show_bug.cgi?id=1408129 I can't open the window to show the choices now.

**Comment by Monikae** [comment]
Oh, that's what causes this :-/

**Comment by NudeSpoons** [comment]
@arantius Users of this extension must be confused that you have retained references to functionality that is no longer available to them.  Certainly, I was, prior to stumbling across these comments.  However, I doubt that most users would think to even check on GitHub.  I suggest you update all references to note the unavailability of these functions.  Otherwise, you are misleading users, albeit inadvertently.

**Comment by pabs3** [comment]
Have you considered adding a page-action popup to replace the navigation options the XUL extension had? I think that would let you have the normal toolbar button that just goes up once plus a button in the URL bar that gives you the choice of what URL to switch to.

If that was done, it feels more logical for the toolbar button to bring up the popup and the page-action button to just go up once, so perhaps they should be swapped around. That would be unexpected for users though, so maybe it should be a preference option.

**Comment by BeecherNetworks** [comment]
I'm using Waterfox, can anyone tell me the last version that supported the dropdown?

EDIT: Seems to be 1.5.8. Now where to find it?

**Comment by pabs3** [comment]
Uppity 1.5.8 was the last version in Debian, it only supported XUL
based Firefox, so I expect that will work in Waterfox and it definitely
had the dropdown.

I don't know which version removed the dropdown, you might want to dig
through the releases to find that out.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by BeecherNetworks** [comment]
I found it in one of the AddOn archives. No releases here, unfortunately. :(

**Comment by gizmecano** [comment]
Closed as _won't fix_ due to [Commands API is not treated as user input](https://bugzilla.mozilla.org/show_bug.cgi?id=1408129).

**Comment by pabs3** [comment]
@gizmecano I don't think this should have been closed, since it is still possible that the Uppity extension could add a page action button (in addition to the toolbar button), that would bring up the URL list for navigation. Its annoying that the two actions need to be separate, but it is still possible to have both.

**Comment by dahamsta** [comment]
I'm using [Navigate Up WE](https://addons.mozilla.org/en-US/firefox/addon/navigate-up-we/) now, which has the list on right-click. I can't remember how Uppity used to do it at this point.

**Comment by gizmecano** [comment]
@pabs3 From a technical point of view, you are probably right. Nevertheless, it doesn't seem that these types of changes have been considered since the opening of this issue: @arantius can always reopen it if he thinks apropriate.
